name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22

          script: |
            cd /var/www

            if [ ! -d "html" ]; then
              git clone https://github.com/rajains234-netizen/GEO_BOOST_ENGINE_LANDINGPAGE.git html
            fi

            cd html
            git pull origin main

            cd frontend
            npm install --legacy-peer-deps --force
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            sudo systemctl restart nginx
